# Generated by Django 4.1 on 2023-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="class_name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(default="testt", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="solutions_sent",
            field=models.SmallIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="solutions_total",
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
