# Generated by Django 4.1 on 2023-06-29 10:19

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_project_class_name_project_project_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link_text",
            field=models.CharField(default="Edit", max_length=4),
        ),
        migrations.AddField(
            model_name="project",
            name="reference",
            field=models.FileField(
                default="reference.mdj",
                upload_to="files/",
                validators=[webapp.validators.validate_mdj],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="solution",
            name="solution_file",
            field=models.FileField(
                upload_to="files/",
                validators=[webapp.validators.validate_mdj],
            ),
        ),
    ]
