# Generated by Django 4.1 on 2023-06-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_project_link_text_project_reference_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="link_text",),
    ]
