# Generated by Django 4.1 on 2023-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_remove_project_link_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dir",
            field=models.CharField(default="1", max_length=7),
            preserve_default=False,
        ),
    ]
