# Generated by Django 4.1 on 2023-07-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_alter_project_class_name_alter_project_project_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="class_name", new_name="group_name",
        ),
    ]
