# Generated by Django 4.1 on 2023-07-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_rename_class_name_project_group_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="score", new_name="grade",
        ),
    ]
