# Generated by Django 4.1 on 2023-07-06 11:43

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_rename_score_student_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="students_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/",
                validators=[webapp.validators.validate_excel],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="dir",
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="reference",
            field=models.FileField(
                upload_to="files/", validators=[webapp.validators.validate_mdj]
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="solution_file",
            field=models.FileField(
                upload_to="files/", validators=[webapp.validators.validate_mdj]
            ),
        ),
    ]
