# Generated by Django 4.1 on 2023-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_student_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reference_list',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
