# Generated by Django 4.1 on 2023-10-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_project_reference_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='given_list',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
